name: "Unit Tests"

on: push

env:
  GO_VERSION: "1.18"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Pull dependencies"
        run: go mod vendor
      - name: "Unit tests"
        run: make test
      - name: "Linter"
        run: make lint
      - name: "Send coverage"
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
